# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# Full reference for Standard Spring Boot properties is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# set -Dspring.profiles.active=<dev|sit|int> as JVM argument to run in desired profile
# If no profile is specified explicitly, application will fall back to default profile, which is "local"

spring:
  application:
    name: spring-boot-aop-sample
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    problemdetails:
      enabled: false
  threads:
    virtual:
      enabled: true

server:
  port: 8090
  forward-headers-strategy: framework
#    servlet:
#        context-path: /api
logging:
  level:
    ROOT: INFO
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here